
services:
  postgres:
    image: postgres:latest
    container_name: leaderboard_postgres
    restart: always
    environment:
      POSTGRES_USER: leaderboard
      POSTGRES_PASSWORD: leaderboard
      POSTGRES_DB: leaderboard
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data